language: "perl"
perl:
    - "5.10"
install: "echo"

script: "perl Configure.pl --backends=moar $NQP_OPTIONS; make test"

branches:
   only:
     - master
     - /smoke-me/

notifications:
  irc:
    channels:
    - "irc.freenode.net#perl6"
    on_success: change
    on_failure: always
    template:
      - "NQP build %{result}. %{author} '%{commit_message}'"
      - "%{build_url} %{compare_url}"


env:
  matrix:
    - NQP_OPTIONS="--gen-moar"
    - NQP_OPTIONS="--gen-moar=master"
    - NQP_OPTIONS="--gen-moar --backends=js,moar"
    - NQP_OPTIONS="--gen-moar=master --backends=js,moar"
